on:
  release:
    types: 
      - published

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runtime:
          - linux-arm
          - linux-arm64
          - linux-x64
          - linux-musl-arm
          - linux-musl-arm64
          - linux-musl-x64
          - osx-arm64
          - osx-x64
          - win-arm
          - win-arm64
          - win-x64
          - win-x86
        include:
          - runs-on: ubuntu-latest
          - runs-on: macos-latest
            runtime: osx-x64
          - runs-on: macos-latest
            runtime: osx-arm64
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8

      - run: |
          dotnet build src/ChangeThis/ChangeThis.csproj -c Release -o bin \
          --sc false -r ${{ matrix.runtime }} -p:DebugType=none \
          -p:PublishSingleFile=true

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.runtime }}-${{ github.sha }}
          path: bin/

  update-release-notes:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v2

      - uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.extract-release-notes.outputs.release_notes }}

  upload-to-release:
    needs:
      - build
      - update-release-notes
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        runtime:
          - linux-arm
          - linux-arm64
          - linux-x64
          - linux-musl-arm
          - linux-musl-arm64
          - linux-musl-x64
          - osx-arm64
          - osx-x64
          - win-arm64
          - win-x64
          - win-x86
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.runtime }}-${{ github.sha }}
          path: artifact/

      - run: |
          cp CHANGELOG.md LICENSE README.md artifact/

      - name: Pack artifact (Windows)
        if: startsWith(matrix.runtime, 'win') == true
        run: |
          zip -r ../${{ github.event.repository.name }}-${{ matrix.runtime }}.zip *
        working-directory: artifact
  
      - name: Pack artifact (Others)
        if: startsWith(matrix.runtime, 'win') == false
        run: |
          tar -czvf ../${{ github.event.repository.name }}-${{ matrix.runtime }}.tar.gz *
        working-directory: artifact

      - name: Upload artifact to release (Windows)
        if: startsWith(matrix.runtime, 'win') == true
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.event.repository.name }}-${{ matrix.runtime }}.zip

      - name: Upload artifact to release (Others)
        if: startsWith(matrix.runtime, 'win') == false
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.event.repository.name }}-${{ matrix.runtime }}.tar.gz
